### ISSUE TITLE
I18n issue

### ISSUE THREAD

**Issue by mmqmzk** [svermeulen/vim-subversive#12]
If using vim other than the English version, [this line](https://github.com/svermeulen/vim-subversive/blob/5837cb38f656f120e7a04ae73f749303d78b9191/autoload/subversive/singleMotion.vim#L10) fails to catch the error when detecting yoink installation.
![Snipaste_2019-08-23_18-24-10](https://user-images.githubusercontent.com/2217694/63586360-b95a8780-c5d3-11e9-841d-bddf8e786d6c.png)

**Comment by gustavo-hms** [comment]
I'm using neovim in Portuguese and have the same issue. It's very annoying having this message popping up every time I use the plugin.

**Comment by svermeulen** [comment]
Ok I think this is fixed now.  Can you try again @gustavo-hms ?

**Comment by gustavo-hms** [comment]
It's working now. Thank you!
