### ISSUE TITLE
How to make visual work with the Substitute Motion

### ISSUE THREAD

**Issue by blasco** [svermeulen/vim-subversive#13]
The mappings provide the following:

```
" s for substitute
nmap s <plug>(SubversiveSubstitute)
nmap ss <plug>(SubversiveSubstituteLine)
nmap S <plug>(SubversiveSubstituteToEndOfLine)
```

Why there are no mappings to substitute the visual selection? Is this not working? Any idea how could it be fixed?

**Comment by blasco** [comment]
I think that the problem might me on my side. I would like to have, s for the normal mode and ss for the selection mode:

```
" s := substitute
nmap s <plug>(SubversiveSubstitute)
" ss := substitue selection
xmap ss <plug>(SubversiveSubstitute)
```
Doesn't seem to be working.

**Comment by svermeulen** [comment]
What you have there should work (`xmap ss <plug>(SubversiveSubstitute)`).  What doesn't work about it?

**Comment by blasco** [comment]
It seems to be working now. Thank you for the support and great plugin!
