### ISSUE TITLE
Plugin will not work if trying to substitute the last line

### ISSUE THREAD

**Issue by theniceboy** [svermeulen/vim-subversive#18]
if you have three lines in your file:
```
aaaa
bbbb
cccc
```

If you press `yy` on line 1 (to copy the first line) and the press `ss` on the third line. The plugin will not work as intended. This will be the result:
```
aaa
aaa
bbb
```

**Comment by svermeulen** [comment]
Yep, you're right.  I can reproduce this too.  Will fix this

**Comment by svermeulen** [comment]
Ok I believe this is fixed now

**Comment by theniceboy** [comment]
Thanks, man! Love the plugin!
