### ISSUE TITLE
[Feature Request] Substitution preview

### ISSUE THREAD

**Issue by 0xC0FFEE** [svermeulen/vim-subversive#6]
Neovim has a feature called `inccommand`, which previews of (among others) the result of the `:substitute` command.

Would it be possible to  support the same for the `:SubversiveSubstitute*` commands?

**Comment by svermeulen** [comment]
That's pretty neat, I didn't know about that command.  I can think of a way to do this, yes

**Comment by svermeulen** [comment]
Ok should work now.  Should use the actual substitute command instead of just a prompt for replacement text when `inccommand` is set, so that the preview occurs

**Comment by 0xC0FFEE** [comment]
Awesome! I'll give it a spin tomorrow, but this looks really promising already :+1:

**Comment by 0xC0FFEE** [comment]
Works like a charm! Thank you for implementing this so quickly.

This really makes the plugin usable for me, as I'm so used to the substitution preview by now. It's highly addictive ;-).

**Comment by svermeulen** [comment]
Ok great good to know

No problem - Thanks for pointing out that neovim feature, I somehow missed that.  I can see why it's addictive
